### ISSUE TITLE
angular ssr causes window is not defined

### ISSUE THREAD

**Issue by julesmercado** [ramon82/zuck.js#104]
/path-to-project/server/main.js:488673
})(window || {});
   ^

ReferenceError: window is not defined
    at Object../node_modules/zuck.js/src/zuck.js (path-to-project/server/main.js:488673:4)
    at __webpack_require__ (path-to-project/server/main.js:20:30)
    at Object../src/app/shared/components/store-detail/store-detail.component.ts (path-to-project/server/main.js:495546:17)
    at __webpack_require__ (path-to-project/server/main.js:20:30)
    at Object../src/app/shared/components/shared-components.module.ts (path-to-project/server/main.js:494085:32)
    at __webpack_require__ (path-to-project/server/main.js:20:30)
    at Object../src/app/app.server.module.ngfactory.js (path-to-project/server/main.js:489137:11)
    at __webpack_require__ (path-to-project/server/main.js:20:30)
    at Object../server.ts (path-to-project/server/main.js:488697:27)
    at __webpack_require__ (path-to-project/server/main.js:20:30)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:52927

-------------------------------------------------------------------------------

 /* Legacy code */
  ZuckJS.buildItem = ZuckJS.buildStoryItem;

  // CommonJS and Node.js module support.
  if (typeof exports !== 'undefined') {
    // Support Node.js specific `module.exports` (which can be a function)
    if (typeof module !== 'undefined' && module.exports) {
      exports = module.exports = ZuckJS;
    }
    // But always support CommonJS module 1.1.1 spec (`exports` cannot be a function)
    exports.ZuckJS = ZuckJS;
  } else {
    /* Too much zuck zuck to maintain legacy */
    window.ZuckitaDaGalera = window.Zuck = ZuckJS;
  }

  return ZuckJS;
})(window || {});
    ^ <--- this seems to be causing the problem

**Comment by ramon82** [comment]
¯\_(ツ)_/¯
